project:
  type: website

website:
  title: "AIMS eReefs"
  favicon: images/ereefs_aims_favicon.png
  navbar:
    title: "AIMS eReefs"
    logo: images/ereefs_logo.png
    background: light
    left:
      - text: eReefs Websites
        menu:
          - href: https://www.ereefs.org.au/
            text: Project Website
          - href: https://research.csiro.au/ereefs/
            text: CSIRO
          - href: http://www.bom.gov.au/environment/activities/reeftemp/reeftemp.shtml
            text: ReefTemp
          - href: https://portal.ereefs.info/map
            text: Interactive Data Portal
      - text: Visualisation Portal
        menu:
          - href: index.qmd
            text: Visualisation Portal
          - href: index.qmd#ereefs-csiro-hydrodynamic-model
            text: Hydrodynamic model
          - href: index.qmd#ereefs-csiro-biogeochemical-model-4-km
            text: BioGeoChemical model
      - href: https://extraction.ereefs.aims.gov.au/?_gl=1*1ag9zj1*_ga*OTM5OTM3MTMzLjE2NjczNTcwNzg.*_ga_6SSTNBNHXG*MTY5MTk2OTEyOC4yNy4wLjE2OTE5NjkxMjguMC4wLjA.
        text: Data Extraction
      - text: Help
        menu:
          - href: help/index.qmd
            text: Visualisation Portal Help
          - href: https://open-aims.github.io/ereefs-tutorials/
            text: Tutorials
          - href: https://extraction.ereefs.aims.gov.au/faqs
            text: Data Extraction FAQs
      - text: About
        menu:
          - href: about.qmd
            text: eReefs AIMS Visualisation Portal
          - href: https://www.ereefs.org.au/
            text: eReefs Program Website
  page-footer:
    background: primary
    left: |
      Colaborators
      <br>[![](/images/logos/AIMS-210x49.png){fig-alt="AIMS"}](https://aims.gov.au/)
      [![](/images/logos/CSIRO-60x60.png){fig-alt="CSIRO"}](https://www.csiro.au/)
      [![](/images/logos/BoM-210x51.png){fig-alt="Beauro of Meteorology"}](http://www.bom.gov.au/)
    center: |
      Funders
      <br>![](/images/logos/Aus-Gov-159x80.png){fig-alt="Australian Government"}
      ![](/images/logos/BHP-BMA-210x51.png){fig-alt="BHP Billiton Mitsubishi Alliance"}
      ![](/images/logos/GBRF_1-210x66.png){fig-alt="Great Barrier Reef Foundation"}
      ![](/images/logos/QLD-Gov-64x80.png){fig-alt="Queensland Government"}
      ![](/images/logos/SIEF-110x66.png){fig-alt="Science and Industry Endowment Fund"}


format:
  html:
    theme: 
       light: flatly
       dark: darkly
    css: 
      - css/ereefs_aims.css
      - css/eatlas_ncanimate2.css
      - css/eatlas_ncanimate2_responsive.css
      - css/custom.scss
      - css/styles.css
    toc: false

execute:
  freeze: auto # ensures code blocks are only executed locally as opposed to being executes as part of GitHub actions
