project:
  type: website

website:
  title: "AIMS eReefs"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - text: More
        menu:
          - index.qmd
          - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false

execute:
  freeze: auto # ensures code blocks are only executed locally as opposed to being executes as part of GitHub actions
